apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: {{ .Values.clusterName }}
  region: {{ .Values.awsRegion }}
  version: {{ .Values.eksVersion | quote }}
  tags:
    karpenter.sh/discovery: {{ .Values.clusterName }}

iam:
  withOIDC: true

addons:
- name: aws-ebs-csi-driver
  version: 1.4.0
  attachPolicy: 
    Statement:
    - Effect: Allow
      Action:
      - ec2:CreateSnapshot
      - ec2:AttachVolume
      - ec2:DetachVolume
      - ec2:ModifyVolume
      - ec2:DescribeAvailabilityZones
      - ec2:DescribeInstances
      - ec2:DescribeSnapshots
      - ec2:DescribeTags
      - ec2:DescribeVolumes
      - ec2:DescribeVolumesModifications
      Resource: "*"
    - Effect: Allow
      Action:
      - ec2:CreateTags
      Resource:
      - arn:aws:ec2:*:*:volume/*
      - arn:aws:ec2:*:*:snapshot/*
      Condition:
        StringEquals:
          ec2:CreateAction:
          - CreateVolume
          - CreateSnapshot
    - Effect: Allow
      Action:
      - ec2:DeleteTags
      Resource:
      - arn:aws:ec2:*:*:volume/*
      - arn:aws:ec2:*:*:snapshot/*
    - Effect: Allow
      Action:
      - ec2:CreateVolume
      Resource: "*"
      Condition:
        StringLike:
          aws:RequestTag/ebs.csi.aws.com/cluster: 'true'
    - Effect: Allow
      Action:
      - ec2:CreateVolume
      Resource: "*"
      Condition:
        StringLike:
          aws:RequestTag/CSIVolumeName: "*"
    - Effect: Allow
      Action:
      - ec2:CreateVolume
      Resource: "*"
      Condition:
        StringLike:
          aws:RequestTag/kubernetes.io/cluster/*: owned
    - Effect: Allow
      Action:
      - ec2:DeleteVolume
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/ebs.csi.aws.com/cluster: 'true'
    - Effect: Allow
      Action:
      - ec2:DeleteVolume
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/CSIVolumeName: "*"
    - Effect: Allow
      Action:
      - ec2:DeleteVolume
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/kubernetes.io/cluster/*: owned
    - Effect: Allow
      Action:
      - ec2:DeleteSnapshot
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/CSIVolumeSnapshotName: "*"
    - Effect: Allow
      Action:
      - ec2:DeleteSnapshot
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/ebs.csi.aws.com/cluster: 'true'

vpc:
  cidr: {{ .Values.vpc.cidr }}
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

managedNodeGroups:
  - name: managed-ng-private-1
    volumeType: gp3
    volumeEncrypted: true
    instanceType: {{ .Values.nodeInstanceType }}
    minSize: 1
    desiredCapacity: 2
    maxSize: 4
    volumeSize: 20
    privateNetworking: true
    updateConfig:
      maxUnavailable: 2
    labels:
      role: worker
    tags:
      nodegroup-role: worker
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/{{ .Values.clusterName }}: "owned"

cloudWatch:
  clusterLogging: 
    enableTypes: ["audit", "api", "authenticator", "controllerManager"]
    logRetentionInDays: 7

# Consider using Karpenter instead of cluster-autoscaler...
karpenter:
  version: "0.5.6"
  createServiceAccount: true