kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: aws-ebs-csi-driver
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
