apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: {{ .Values.clusterName }}
  region: {{ .Values.awsRegion }}
  version: {{ .Values.eksVersion | quote }}
  tags:
    karpenter.sh/discovery: {{ .Values.clusterName }}
    {{- range $key, $value := .Values.tags }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

iam:
  withOIDC: true

{{- if .Values.addons.ebsCsiDriver.enabled }}
addons:
- name: aws-ebs-csi-driver
  version: {{ .Values.addons.ebsCsiDriver.version }}
  attachPolicy: 
    Statement:
    - Effect: Allow
      Action:
      - ec2:CreateSnapshot
      - ec2:AttachVolume
      - ec2:DetachVolume
      - ec2:ModifyVolume
      - ec2:DescribeAvailabilityZones
      - ec2:DescribeInstances
      - ec2:DescribeSnapshots
      - ec2:DescribeTags
      - ec2:DescribeVolumes
      - ec2:DescribeVolumesModifications
      Resource: "*"
    - Effect: Allow
      Action:
      - ec2:CreateTags
      Resource:
      - arn:aws:ec2:*:*:volume/*
      - arn:aws:ec2:*:*:snapshot/*
      Condition:
        StringEquals:
          ec2:CreateAction:
          - CreateVolume
          - CreateSnapshot
    - Effect: Allow
      Action:
      - ec2:DeleteTags
      Resource:
      - arn:aws:ec2:*:*:volume/*
      - arn:aws:ec2:*:*:snapshot/*
    - Effect: Allow
      Action:
      - ec2:CreateVolume
      Resource: "*"
      Condition:
        StringLike:
          aws:RequestTag/ebs.csi.aws.com/cluster: 'true'
    - Effect: Allow
      Action:
      - ec2:CreateVolume
      Resource: "*"
      Condition:
        StringLike:
          aws:RequestTag/CSIVolumeName: "*"
    - Effect: Allow
      Action:
      - ec2:CreateVolume
      Resource: "*"
      Condition:
        StringLike:
          aws:RequestTag/kubernetes.io/cluster/*: owned
    - Effect: Allow
      Action:
      - ec2:DeleteVolume
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/ebs.csi.aws.com/cluster: 'true'
    - Effect: Allow
      Action:
      - ec2:DeleteVolume
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/CSIVolumeName: "*"
    - Effect: Allow
      Action:
      - ec2:DeleteVolume
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/kubernetes.io/cluster/*: owned
    - Effect: Allow
      Action:
      - ec2:DeleteSnapshot
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/CSIVolumeSnapshotName: "*"
    - Effect: Allow
      Action:
      - ec2:DeleteSnapshot
      Resource: "*"
      Condition:
        StringLike:
          ec2:ResourceTag/ebs.csi.aws.com/cluster: 'true'
{{- end }}

vpc:
  cidr: {{ .Values.vpc.cidr }}
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

managedNodeGroups:
  - name: managed-ng-private-1
    volumeType: {{ .Values.managedNodeGroup.volumeType }}
    volumeEncrypted: {{ .Values.managedNodeGroup.volumeEncrypted }}
    instanceType: {{ .Values.nodeInstanceType }}
    minSize: {{ .Values.managedNodeGroup.minSize }}
    desiredCapacity: {{ .Values.managedNodeGroup.desiredCapacity }}
    maxSize: {{ .Values.managedNodeGroup.maxSize }}
    volumeSize: {{ .Values.managedNodeGroup.volumeSize }}
    privateNetworking: true
    updateConfig:
      maxUnavailable: 2
    labels:
      role: worker
    tags:
      nodegroup-role: worker
      {{- range $key, $value := .Values.tags }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}

cloudWatch:
  clusterLogging: 
    enableTypes: {{ .Values.logging.enableTypes | toJson }}
    logRetentionInDays: {{ .Values.logging.retentionDays }}

karpenter:
  version: {{ .Values.karpenter.version | quote }}
  createServiceAccount: true