apiVersion: v2
name: eks-accelerator
description: EKS cluster with Karpenter autoscaling
type: application
version: 1.0.0
appVersion: 1.31.0
keywords:
  - eks
  - kubernetes
  - karpenter
  - aws
maintainers:
  - name: EKS-Accelerator Team