# karpenter is extensible via the spec section of the provisioner. documentation for the provisioner api is found https://karpenter.sh/v0.7.2/provisioner/
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Values.provisionerName }}
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      # Can be spot or on demand or both
      values: {{ .Values.deploymentType }}  
#  limits:
#    resources:
#      cpu: 1000
  provider:
    launchTemplate: KarpenterCustomLaunchTemplate
    subnetSelector:
      kubernetes.io/role/internal-elb: '1'
    securityGroupSelector:
      karpenter.sh/discovery: {{ .Values.clusterName }}
    instanceProfile: eksctl-KarpenterNodeInstanceProfile-{{ .Values.clusterName }}
  ttlSecondsAfterEmpty: {{ .Values.ttlSecondsAfterEmpty }}
